version: "3"
services:
  frontend:
    container_name: frontend
    image: mjw0lf/is-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443

  backend:
    restart: always
    container_name: backend
    image: mjw0lf/is-server
    build:
      context: ./server
      dockerfile: Dockerfile